# Site settings
title: Moonshadow 
email: hwwangwang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
        居然开始写Blog了
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: moonshadow520
github_username:  moonshadow

# Build settings
markdown: kramdown
